# !/usr/bin/env python

# Copyright 2026 NVIDIA Corporation and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""In-headset HUD for the Isaac Teleop -> SO-101 examples (Televiz / ``isaacteleop.viz``).

The operator wearing the headset cannot read the terminal, so every state the loop
prints — preflight instructions, pose-lost warnings, clutch state — must ALSO render
inside the CloudXR session. This module provides both halves:

* :class:`HudClient` (imported by ``common.py``): spawns ``hud.py`` as a subprocess and
  streams JSON state lines to its stdin. The subprocess owns its own OpenXR session via
  ``isaacteleop.viz`` — the same multi-client pattern as IsaacTeleop's ``camera_viz``
  example, where the teleop process holds a *headless* session (trackers only) and a
  second process submits composited layers to the same CloudXR runtime.
* The server ``main()`` (this file run as a script): one RGBA quad layer, lazily
  re-anchored to the head pose, re-rendered with PIL whenever the state changes.

The HUD is strictly best-effort: the teleop loop never blocks on it, a dead or missing
HUD process degrades to terminal-only output, and ``isaacteleop.viz`` (a ``BUILD_VIZ=ON``
wheel) is NOT a hard dependency of the example.

State protocol (one JSON object per line on stdin; all fields optional):

``phase``
    ``connect | preflight | follower | reset | teleop | pose_lost | fail | bye``.
``instruction`` / ``detail``
    Big center text and a smaller line under it.
``severity``
    ``info | ok | warn | error`` — drives the border/accent color.
``checks_done`` / ``checks_total`` / ``attempt``
    Preflight progress row (dots) and attempt counter.
``engaged`` / ``squeeze`` / ``trigger`` / ``lead_cm``
    Teleop-phase compact status (clutch state and how far the target leads the arm).
``waiting``
    Preflight is paused waiting for the VR stream (dims the panel).
"""

from __future__ import annotations

import json
import math
import subprocess
import sys
import threading
import time
from contextlib import suppress
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------- rendering

# Panel pixel resolution (16:9). Mipmaps are generated by the compositor, so the panel
# stays readable when the operator moves away from it.
PANEL_W, PANEL_H = 800, 450

# Panel placement relative to the head: distance forward [m], vertical offset [m], and
# world width [m] (height follows the pixel aspect ratio).
PANEL_DISTANCE_M = 1.15
PANEL_Y_OFFSET_M = -0.12
PANEL_WIDTH_M = 0.62

# Aim laser-dot layer: a small quad laid flat on the table plane at the point the
# controller's aim ray hits (the operator's "where am I pointing" endpoint). Its
# anchor-frame pose arrives precomputed in the `aim_dot` field of teleop states;
# when hidden the quad parks far underground instead of being detached (cheaper
# than add/remove per frame, invisible behind the guardian floor).
DOT_PX = 64
DOT_SIZE_M = 0.035
DOT_PARK_POSE = ((0.0, -100.0, 0.0), (1.0, 0.0, 0.0, 0.0))

# Lazy re-anchor policy: glide to a new anchor when the head has turned this far away
# from the panel bearing (or moved this far), after a short dwell so quick glances
# don't drag the panel around.
REANCHOR_ANGLE_DEG = 28.0
REANCHOR_DISTANCE_M = 0.35
REANCHOR_DWELL_S = 0.4
GLIDE_S = 0.35

_FONT_DIR = Path("/usr/share/fonts/truetype/dejavu")

# severity -> (border RGBA, accent RGB)
_SEVERITY_COLORS = {
    "info": ((90, 130, 200, 255), (120, 170, 255)),
    "ok": ((70, 190, 110, 255), (110, 230, 150)),
    "warn": ((230, 180, 60, 255), (255, 210, 90)),
    "error": ((230, 70, 60, 255), (255, 110, 100)),
}

_PHASE_TITLES = {
    "connect": "CONNECTING",
    "preflight": "PREFLIGHT CHECK",
    "follower": "FOLLOWER CHECK",
    "reset": "RESETTING ARM",
    "teleop": "TELEOP",
    "pose_lost": "POSE LOST",
    "fail": "FAILED",
}


def _load_fonts():
    """DejaVu (present on stock Ubuntu); PIL's default bitmap font as a last resort."""
    from PIL import ImageFont

    try:
        bold = _FONT_DIR / "DejaVuSans-Bold.ttf"
        sans = _FONT_DIR / "DejaVuSans.ttf"
        return {
            "title": ImageFont.truetype(str(bold), 40),
            "body": ImageFont.truetype(str(bold), 34),
            "detail": ImageFont.truetype(str(sans), 26),
            "small": ImageFont.truetype(str(sans), 22),
        }
    except OSError:
        fallback = ImageFont.load_default()
        return {"title": fallback, "body": fallback, "detail": fallback, "small": fallback}


def _wrap(draw, text: str, font, max_w: int) -> list[str]:
    """Greedy word wrap by rendered pixel width."""
    lines: list[str] = []
    for para in text.split("\n"):
        words = para.split()
        if not words:
            lines.append("")
            continue
        cur = words[0]
        for word in words[1:]:
            cand = f"{cur} {word}"
            if draw.textlength(cand, font=font) <= max_w:
                cur = cand
            else:
                lines.append(cur)
                cur = word
        lines.append(cur)
    return lines


def _as_float(value) -> float | None:
    """Defensive number parse — a malformed state field must never kill the HUD."""
    try:
        f = float(value)
    except (TypeError, ValueError):
        return None
    return f if math.isfinite(f) else None


def _draw_heading_compass(draw, fonts, *, yaw_deg, pitch_deg, engaged: bool, accent) -> None:
    """Top-down compass showing where the controller points in the ROBOT base frame.

    Yaw convention matches ``common._heading_deg``: 0 deg = robot +X (forward) = compass
    UP; +90 deg = robot +Y (left) = compass LEFT (top-down view of a Z-up base frame, so
    positive yaw sweeps counter-clockwise on screen). The pitch readout is numeric
    (+ = up). Skipped entirely when yaw is missing/non-finite so older senders and
    malformed frames degrade to the previous layout.
    """
    if yaw_deg is None:
        return
    cx, cy, r = 668, 210, 62
    ring = (90, 90, 90, 255)
    needle = _SEVERITY_COLORS["ok"][1] if engaged else (170, 170, 170, 255)
    draw.ellipse([cx - r, cy - r, cx + r, cy + r], outline=ring, width=2)
    # Cardinal marks: robot +X (front) up, +Y (left) on the left of the dial.
    draw.text((cx - 6, cy - r - 24), "+X", font=fonts["small"], fill=(150, 150, 150, 255))
    draw.text((cx - r - 30, cy - 9), "+Y", font=fonts["small"], fill=(120, 120, 120, 255))
    # Needle: screen x = -sin(yaw) (positive yaw -> left), screen y = -cos(yaw) (0 -> up).
    a = math.radians(yaw_deg)
    tip = (cx - (r - 8) * math.sin(a), cy - (r - 8) * math.cos(a))
    tail = (cx + 14 * math.sin(a), cy + 14 * math.cos(a))
    draw.line([tail, tip], fill=needle, width=5)
    draw.ellipse([tip[0] - 5, tip[1] - 5, tip[0] + 5, tip[1] + 5], fill=needle)
    draw.ellipse([cx - 4, cy - 4, cx + 4, cy + 4], fill=ring)
    label = f"yaw {yaw_deg:+.0f}"
    if pitch_deg is not None:
        label += f"  pitch {pitch_deg:+.0f}"
    draw.text(
        (cx - draw.textlength(label, font=fonts["small"]) / 2, cy + r + 8),
        label,
        font=fonts["small"],
        fill=(190, 190, 190, 255),
    )


def render_hud(state: dict, fonts=None) -> np.ndarray:
    """Render one HUD frame from a state dict -> (PANEL_H, PANEL_W, 4) uint8 RGBA.

    Pure given ``state`` (no XR/session access) and defensive against malformed fields —
    the HUD must degrade, never raise, whatever the loop feeds it. Unit-testable headless.
    """
    from PIL import Image, ImageDraw

    if fonts is None:
        fonts = _load_fonts()

    phase = str(state.get("phase", "connect"))
    severity = str(state.get("severity", "info"))
    if severity not in _SEVERITY_COLORS:
        severity = "info"
    border, accent = _SEVERITY_COLORS[severity]
    dim = bool(state.get("waiting", False))

    img = Image.new("RGBA", (PANEL_W, PANEL_H), (12, 14, 20, 215))
    draw = ImageDraw.Draw(img)
    draw.rounded_rectangle([3, 3, PANEL_W - 4, PANEL_H - 4], radius=18, outline=border, width=6)

    title = str(state.get("title") or _PHASE_TITLES.get(phase, phase.upper()))
    draw.text((36, 26), title, font=fonts["title"], fill=accent)
    attempt = _as_float(state.get("attempt", 0))
    if attempt is not None and attempt > 1:
        tag = f"attempt {int(attempt)}"
        draw.text(
            (PANEL_W - 36 - draw.textlength(tag, font=fonts["small"]), 40),
            tag,
            font=fonts["small"],
            fill=(200, 200, 200, 255),
        )
    draw.line([36, 84, PANEL_W - 36, 84], fill=border, width=2)

    text_color = (150, 150, 150, 255) if dim else (240, 240, 240, 255)

    if phase == "teleop":
        engaged = bool(state.get("engaged", False))
        stateline = "ENGAGED" if engaged else "idle — squeeze the grip to engage"
        color = _SEVERITY_COLORS["ok"][1] if engaged else (170, 170, 170)
        draw.text((36, 116), stateline, font=fonts["body"], fill=color)
        # Motion-scale chip (thumbstick up/down changes it): always visible so the
        # operator can tell precision mode is on before wondering why the arm is "slow".
        speed = _as_float(state.get("speed_scale"))
        if speed is not None:
            chip = f"x{speed:.2f}".rstrip("0").rstrip(".")
            chip_w = draw.textlength(chip, font=fonts["body"])
            cx0, cy0 = 36, 158
            highlight = abs(speed - 1.0) > 1e-6  # non-1:1 scale deserves attention
            chip_color = (255, 190, 80) if highlight else (150, 150, 150)
            draw.rounded_rectangle(
                [cx0 - 8, cy0 - 4, cx0 + chip_w + 8, cy0 + 30], radius=8, outline=chip_color, width=2
            )
            draw.text((cx0, cy0), chip, font=fonts["body"], fill=chip_color)
            draw.text(
                (cx0 + chip_w + 20, cy0 + 4),
                "stick up/down = speed",
                font=fonts["small"],
                fill=(120, 120, 120, 255),
            )
        _draw_heading_compass(
            draw,
            fonts,
            yaw_deg=_as_float(state.get("yaw_deg")),
            pitch_deg=_as_float(state.get("pitch_deg")),
            engaged=engaged,
            accent=accent,
        )
        y = 210
        for label, value in (("squeeze", state.get("squeeze")), ("trigger", state.get("trigger"))):
            frac = _as_float(value)
            if frac is None:
                continue
            frac = max(0.0, min(1.0, frac))
            draw.text((36, y), label, font=fonts["small"], fill=(190, 190, 190, 255))
            draw.rectangle([160, y + 4, 560, y + 20], outline=(90, 90, 90, 255), width=1)
            draw.rectangle([160, y + 4, 160 + int(400 * frac), y + 20], fill=accent)
            y += 44
        lead = _as_float(state.get("lead_cm"))
        if lead is not None:
            lead_color = (255, 190, 80) if lead > 5.0 else (190, 190, 190)
            draw.text((36, y), f"target leads arm {lead:.1f} cm", font=fonts["small"], fill=lead_color)
        detail = str(state.get("detail", ""))
        if detail:
            draw.text((36, PANEL_H - 66), detail, font=fonts["small"], fill=(190, 190, 190, 255))
    else:
        instruction = str(state.get("instruction", ""))
        y = 116
        for line in _wrap(draw, instruction, fonts["body"], PANEL_W - 72)[:4]:
            draw.text((36, y), line, font=fonts["body"], fill=text_color)
            y += 46
        detail = str(state.get("detail", ""))
        if detail:
            for line in _wrap(draw, detail, fonts["detail"], PANEL_W - 72)[:2]:
                draw.text((36, y + 10), line, font=fonts["detail"], fill=(185, 185, 185, 255))
                y += 36
        total = _as_float(state.get("checks_total", 0))
        total = int(total) if total is not None else 0
        if total > 0:
            done_f = _as_float(state.get("checks_done", 0))
            done = max(0, min(total, int(done_f))) if done_f is not None else 0
            r, gap = 14, 46
            x0 = (PANEL_W - (total - 1) * gap) // 2
            cy = PANEL_H - 64
            for i in range(total):
                cx = x0 + i * gap
                if i < done:
                    draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=_SEVERITY_COLORS["ok"][1])
                elif i == done and not dim:
                    draw.ellipse([cx - r, cy - r, cx + r, cy + r], outline=accent, width=4)
                else:
                    draw.ellipse([cx - r, cy - r, cx + r, cy + r], outline=(110, 110, 110, 255), width=2)
        if dim:
            draw.text(
                (36, PANEL_H - 110),
                "waiting for the VR stream — press Play",
                font=fonts["small"],
                fill=(255, 210, 90, 255),
            )

    return np.asarray(img, dtype=np.uint8).copy()


# ---------------------------------------------------------------------------- client


class HudClient:
    """Parent-side handle: spawns the HUD subprocess and streams JSON state lines.

    Strictly best-effort — ``send()`` never raises and never blocks the control loop;
    the first pipe failure disables the client with a single notice.
    """

    def __init__(self, proc: subprocess.Popen) -> None:
        self._proc = proc
        self._dead = False
        self._last_payload: str | None = None

    @classmethod
    def spawn(cls, mode: str = "xr") -> HudClient | None:
        """Start ``hud.py`` as a subprocess; None when the viz wheel is unavailable.

        Must be called AFTER the teleop device connected, so the child inherits the
        CloudXR runtime env (XR_RUNTIME_JSON, ...) — same reasoning as the so101_leader
        plugin launch in ``common.py``.
        """
        try:
            import isaacteleop.viz  # noqa: F401  (probe only: is this a BUILD_VIZ=ON wheel?)
        except ImportError:
            print("[hud] isaacteleop.viz not available (wheel built without BUILD_VIZ) — terminal only.")
            return None
        proc = subprocess.Popen(
            [sys.executable, str(Path(__file__).resolve().parent / "hud.py"), "--mode", mode],
            stdin=subprocess.PIPE,
            text=True,
        )
        return cls(proc)

    def send(self, state: dict) -> None:
        """Queue one state update; drops silently once the HUD process is gone."""
        if self._dead:
            return
        payload = json.dumps(state, separators=(",", ":"), sort_keys=True)
        if payload == self._last_payload:  # dedupe: the server re-presents the last frame anyway
            return
        try:
            assert self._proc.stdin is not None
            self._proc.stdin.write(payload + "\n")
            self._proc.stdin.flush()
            self._last_payload = payload
        except (OSError, ValueError, AssertionError):
            self._dead = True
            print("[hud] HUD process is gone — falling back to terminal-only output.")

    def close(self) -> None:
        """EOF the pipe (server exits its reader loop) and reap, killing on timeout."""
        if self._proc.stdin is not None:
            with suppress(OSError):
                self._proc.stdin.close()
        try:
            self._proc.wait(timeout=3.0)
        except subprocess.TimeoutExpired:
            self._proc.kill()


# ---------------------------------------------------------------------------- placement


@dataclass
class LazyFollow:
    """Head-locked-but-lazy quad placement (compact port of camera_viz's lazy strategy).

    The panel stays world-anchored in front of the operator and only glides to a new
    anchor after the head has pointed away for ``REANCHOR_DWELL_S`` (or moved far) —
    quick glances at the robot don't drag the panel around.
    """

    anchor_pos: np.ndarray | None = None
    anchor_yaw: float = 0.0
    _glide_from: tuple[np.ndarray, float] | None = None
    _glide_t0: float = 0.0
    _away_since: float | None = field(default=None)

    @staticmethod
    def _target(head_pos: np.ndarray, head_quat_wxyz: np.ndarray) -> tuple[np.ndarray, float]:
        """Anchor pose for the current head: forward on the horizontal plane, facing back."""
        w, x, y, z = head_quat_wxyz
        # Head forward = rotate (0, 0, -1) by the head quaternion (OpenXR: right-handed, Y up).
        fwd = np.array([-2.0 * (x * z + w * y), -2.0 * (y * z - w * x), -(1.0 - 2.0 * (x * x + y * y))])
        horiz = np.array([fwd[0], 0.0, fwd[2]])
        n = float(np.linalg.norm(horiz))
        if n < 1e-3:  # looking straight up/down: keep the previous bearing
            horiz, n = np.array([0.0, 0.0, -1.0]), 1.0
        horiz /= n
        pos = head_pos + horiz * PANEL_DISTANCE_M + np.array([0.0, PANEL_Y_OFFSET_M, 0.0])
        yaw = math.atan2(-horiz[0], -horiz[2])  # quad +Z (its normal) points back at the head
        return pos, yaw

    def update(self, head_pos, head_quat_wxyz, now: float) -> tuple[np.ndarray, float]:
        """Advance one frame; returns (panel position, panel yaw)."""
        head_pos = np.asarray(head_pos, dtype=float)
        target_pos, target_yaw = self._target(head_pos, np.asarray(head_quat_wxyz, dtype=float))

        if self.anchor_pos is None:
            self.anchor_pos, self.anchor_yaw = target_pos, target_yaw
            return self.anchor_pos, self.anchor_yaw

        if self._glide_from is not None:
            t = (now - self._glide_t0) / GLIDE_S
            if t >= 1.0:
                self._glide_from = None
            else:
                s = t * t * (3.0 - 2.0 * t)  # smoothstep
                from_pos, from_yaw = self._glide_from
                dyaw = math.remainder(self.anchor_yaw - from_yaw, math.tau)
                return from_pos + (self.anchor_pos - from_pos) * s, from_yaw + dyaw * s
            return self.anchor_pos, self.anchor_yaw

        angle = abs(math.remainder(target_yaw - self.anchor_yaw, math.tau))
        dist = float(np.linalg.norm(target_pos - self.anchor_pos))
        if angle > math.radians(REANCHOR_ANGLE_DEG) or dist > REANCHOR_DISTANCE_M:
            if self._away_since is None:
                self._away_since = now
            elif now - self._away_since >= REANCHOR_DWELL_S:
                self._glide_from = (self.anchor_pos, self.anchor_yaw)
                self._glide_t0 = now
                self.anchor_pos, self.anchor_yaw = target_pos, target_yaw
                self._away_since = None
        else:
            self._away_since = None
        return self.anchor_pos, self.anchor_yaw


# ---------------------------------------------------------------------------- server


def _render_dot() -> np.ndarray:
    """The laser-dot texture: a soft green disc with a bright core, alpha-feathered."""
    yy, xx = np.mgrid[0:DOT_PX, 0:DOT_PX].astype(float)
    c = (DOT_PX - 1) / 2.0
    r = np.sqrt((xx - c) ** 2 + (yy - c) ** 2) / c  # 0 at center, 1 at edge
    rgba = np.zeros((DOT_PX, DOT_PX, 4), dtype=np.uint8)
    core = np.clip(1.0 - r * 1.4, 0.0, 1.0)  # bright core fading out
    rgba[..., 0] = (90 + 120 * core).astype(np.uint8)
    rgba[..., 1] = 255
    rgba[..., 2] = (90 + 120 * core).astype(np.uint8)
    rgba[..., 3] = (np.clip(1.0 - r, 0.0, 1.0) ** 0.7 * 255).astype(np.uint8)
    return rgba


def _serve(mode: str) -> int:
    """Own an OpenXR/window/offscreen viz session; render states arriving on stdin."""
    import isaacteleop.viz as viz
    import torch  # QuadLayer.submit requires device memory (host buffers are rejected)

    cfg = viz.VizSessionConfig()
    cfg.app_name = "so101_hud"
    if mode == "xr":
        cfg.mode = viz.DisplayMode.kXr
        cfg.xr_near_z, cfg.xr_far_z = 0.05, 100.0
        # The headset may still be connecting when we start; wait for the XR system.
        cfg.xr_system_wait_seconds = 600
    elif mode == "window":
        cfg.mode = viz.DisplayMode.kWindow
        cfg.window_width, cfg.window_height = PANEL_W, PANEL_H
    else:
        cfg.mode = viz.DisplayMode.kOffscreen
    session = viz.VizSession.create(cfg)

    layer_cfg = viz.QuadLayerConfig()
    layer_cfg.name = "so101_hud"
    layer_cfg.resolution = viz.Resolution(PANEL_W, PANEL_H)
    layer_cfg.format = viz.PixelFormat.kRGBA8
    layer = session.add_quad_layer(layer_cfg)

    # Laser-dot layer: texture submitted once, pose moved per frame from the state's
    # precomputed anchor-frame aim_dot (parked underground while there is no hit).
    dot_cfg = viz.QuadLayerConfig()
    dot_cfg.name = "so101_hud_aim_dot"
    dot_cfg.resolution = viz.Resolution(DOT_PX, DOT_PX)
    dot_cfg.format = viz.PixelFormat.kRGBA8
    dot_layer = session.add_quad_layer(dot_cfg)
    dot_layer.submit(torch.from_numpy(_render_dot()).cuda())
    dot_layer.set_placement(viz.QuadLayerPlacement(viz.Pose3D(*DOT_PARK_POSE), (DOT_SIZE_M, DOT_SIZE_M)))

    fonts = _load_fonts()
    follow = LazyFollow()
    panel_size = (PANEL_WIDTH_M, PANEL_WIDTH_M * PANEL_H / PANEL_W)

    state: dict = {"phase": "connect", "instruction": "Waiting for the teleop loop…"}
    state_version = 0
    rendered_version = -1
    rendered_fingerprint: str | None = None
    lock = threading.Lock()
    stop = threading.Event()

    def _read_stdin() -> None:
        nonlocal state, state_version
        for line in sys.stdin:
            line = line.strip()
            if not line:
                continue
            try:
                new_state = json.loads(line)
            except json.JSONDecodeError:
                continue
            if new_state.get("phase") == "bye":
                break
            with lock:
                state = new_state
                state_version += 1
        stop.set()  # EOF or bye: the parent is gone / shutting down

    reader = threading.Thread(target=_read_stdin, name="hud_stdin", daemon=True)
    reader.start()

    print(f"[hud] session up (mode={mode})", file=sys.stderr, flush=True)
    while not stop.is_set():
        with lock:
            current, version = state, state_version
        if version != rendered_version:
            # Split the panel render from the dot placement: the dot moves at aiming
            # rate (many updates/s), re-rendering the 800x450 PIL panel for each would
            # burn CPU for identical pixels. Only re-render when the panel fields changed.
            dot = current.get("aim_dot")
            panel_state = {k: v for k, v in current.items() if k != "aim_dot"}
            fingerprint = json.dumps(panel_state, sort_keys=True, separators=(",", ":"))
            if fingerprint != rendered_fingerprint:
                layer.submit(torch.from_numpy(render_hud(panel_state, fonts)).cuda())
                rendered_fingerprint = fingerprint
            # Laser dot: `aim_dot` = {"pos": [x,y,z], "quat_wxyz": [w,x,y,z]} in the
            # anchor frame, precomputed by the teleop loop; absent/None = no hit -> park.
            try:
                if dot:
                    dot_layer.set_placement(
                        viz.QuadLayerPlacement(
                            viz.Pose3D(tuple(dot["pos"]), tuple(dot["quat_wxyz"])),
                            (DOT_SIZE_M, DOT_SIZE_M),
                        )
                    )
                else:
                    dot_layer.set_placement(
                        viz.QuadLayerPlacement(viz.Pose3D(*DOT_PARK_POSE), (DOT_SIZE_M, DOT_SIZE_M))
                    )
            except (KeyError, TypeError, ValueError):
                pass  # malformed aim_dot: keep the previous placement (best-effort HUD)
            rendered_version = version
        if session.is_xr_mode():
            head = session.head_pose_now()
            if head is not None:
                # Pose3D.orientation is (w, x, y, z).
                pos, yaw = follow.update(
                    np.asarray(head.position), np.asarray(head.orientation), time.monotonic()
                )
                placement = viz.QuadLayerPlacement(
                    viz.Pose3D(tuple(pos), (math.cos(yaw / 2.0), 0.0, math.sin(yaw / 2.0), 0.0)),
                    panel_size,
                )
                layer.set_placement(placement)
            session.render()  # paced by xrWaitFrame
        else:
            session.render()
            time.sleep(1.0 / 30.0)
        if session.should_close():
            stop.set()

    # Same lifecycle rule as camera_viz: never destroy() with a thread possibly inside
    # render(); the reader is daemon and blocked on stdin, so destroying here is safe.
    session.destroy()
    return 0


def _self_test() -> int:
    """Headless proof: render every phase, composite offscreen, verify non-blank pixels."""
    import isaacteleop.viz as viz
    import torch

    cfg = viz.VizSessionConfig()
    cfg.mode = viz.DisplayMode.kOffscreen
    cfg.app_name = "so101_hud_selftest"
    session = viz.VizSession.create(cfg)
    layer_cfg = viz.QuadLayerConfig()
    layer_cfg.name = "so101_hud"
    layer_cfg.resolution = viz.Resolution(PANEL_W, PANEL_H)
    layer_cfg.format = viz.PixelFormat.kRGBA8
    layer = session.add_quad_layer(layer_cfg)
    fonts = _load_fonts()

    states = [
        {"phase": "connect", "instruction": "Waiting for the headset…"},
        {
            "phase": "preflight",
            "instruction": "hold the controller STILL for 1.5 s.",
            "checks_done": 2,
            "checks_total": 6,
            "attempt": 2,
        },
        {"phase": "preflight", "instruction": "…", "checks_total": 6, "waiting": True},
        {"phase": "follower", "instruction": "wiggling the gripper…", "severity": "info"},
        {"phase": "teleop", "engaged": True, "squeeze": 0.8, "trigger": 0.3, "lead_cm": 6.1},
        {"phase": "pose_lost", "severity": "error", "instruction": "Controller out of view — arm held."},
    ]
    frames: list[np.ndarray] = []
    for st in states:
        rgba = render_hud(st, fonts)
        assert rgba.shape == (PANEL_H, PANEL_W, 4), rgba.shape
        assert int(np.count_nonzero(rgba[..., 3])) > 0, f"blank alpha for {st['phase']}"
        layer.submit(torch.from_numpy(rgba).cuda())
        session.render()
        out = np.asarray(session.readback_to_host()).copy()
        # Brighter than the panel's own background (46 summed) -> actual text/graphics.
        lit = int(np.count_nonzero(out[..., :3].sum(axis=-1) > 120))
        print(f"[self-test] {st['phase']:>10}: {lit} bright pixels")
        assert lit > 2000, f"phase {st['phase']} did not composite any content"
        frames.append(out)
    # Every state must produce a DISTINCT composited frame (proves the pipeline is live,
    # not re-presenting one stale texture).
    for i in range(1, len(frames)):
        diff = int(np.count_nonzero(frames[i] != frames[i - 1]))
        assert diff > 1000, f"frames {i - 1} and {i} are identical — stale texture?"
    session.destroy()
    print("[self-test] PASS")
    return 0


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description="SO-101 teleop in-headset HUD (Televiz)")
    parser.add_argument("--mode", choices=("xr", "window", "offscreen"), default="xr")
    parser.add_argument("--self-test", action="store_true", help="offscreen render/composite check")
    args = parser.parse_args(argv)
    if args.self_test:
        return _self_test()
    return _serve(args.mode)


if __name__ == "__main__":
    sys.exit(main())
